name: Auto Build & Release

on:
  workflow_dispatch:
  push:
    paths:
      - version  # 当 version 文件被修改 push 时触发

permissions:
  contents: write
  packages: write

jobs:
  set-release-version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.set_version.outputs.release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Read version file
        id: set_version
        run: |
          version=$(cat version)
          echo "Using version: $version"
          echo "release_version=$version" >> $GITHUB_OUTPUT

  build-go-binary:
    needs: set-release-version
    runs-on: ubuntu-latest
    env:
      BIN_NAME: iptest
      RELEASE_VERSION: ${{ needs.set-release-version.outputs.release_version }}
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm, 386]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm
            goos: darwin

    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21
          binary_name: ${{ env.BIN_NAME }}
          ldflags: -s -w -X "main.version=${{ env.RELEASE_VERSION }}"
          md5sum: false
          release_name: "${{ env.BIN_NAME }} ${{ env.RELEASE_VERSION }}"
          release_tag: ${{ env.RELEASE_VERSION }}
          asset_name: "${{ env.BIN_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          compress_assets: true
