name: Auto Build & Release

on:
  # workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # 需要打包的系统
        goarch: [amd64, arm64, 386, arm] # 需要打包的架构
        exclude:
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: arm
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm

    steps:
      - uses: actions/checkout@v4
      
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21 # 可以指定编译使用的 Golang 版本
          binary_name: iptest # 可以指定二进制文件的名称
          asset_name: iptest-${{ matrix.goos }}-${{ matrix.goarch }}
          ldflags: -s -w -X "main.version=${{ github.ref_name }}"
          md5sum: false
